In [1]:
import pandas as pd
import numpy as np

# 相似度度量

## 余弦相似度

In [2]:
from sklearn.metrics.pairwise import cosine_similarity
i = [1, 0, 0, 0]
j = [1, 0.5, 0.5, 0]
cosine_similarity([i, j])

array([[1.        , 0.81649658],
       [0.81649658, 1.        ]])

## 皮尔逊相关系数

In [3]:
from scipy.stats import pearsonr

i = [1, 0, 0, 0]
j = [1, 0.5, 0.5, 0]
pearsonr(i, j)
# 返回值：（皮尔逊相关系数，p-value）

(0.816496580927726, 0.18350341907227397)

## 构造数据集，矩阵内容是用户对物品的评分

In [4]:
def loadData():
    ratings={'Alice': {'A': 5, 'B': 3, 'C': 4, 'D': 4},
           'Bob': {'A': 3, 'B': 1, 'C': 2, 'D': 3, 'E': 3},
           'Jack': {'A': 4, 'B': 3, 'C': 4, 'D': 3, 'E': 5},
           'Nancy': {'A': 3, 'B': 3, 'C': 1, 'D': 5, 'E': 4},
           'David': {'A': 1, 'B': 5, 'C': 5, 'D': 2, 'E': 1}
          }
    return ratings

ratings= loadData()
ratings = pd.DataFrame(ratings).T

In [5]:
ratings

A    B    C    D    E
Alice  5.0  3.0  4.0  4.0  NaN
Bob    3.0  1.0  2.0  3.0  3.0
Jack   4.0  3.0  4.0  3.0  5.0
Nancy  3.0  3.0  1.0  5.0  4.0
David  1.0  5.0  5.0  2.0  1.0

In [11]:
# Bob与David的相似性
cos_similarity = cosine_similarity([ratings.loc['Bob',:],ratings.loc['David',:]])
psn_similarity = pearsonr(ratings.loc['Bob',:],ratings.loc['David',:])

print('Bob与David的cosine相似度矩阵:')
print(cos_similarity,'\n')
print(f'Bob与David的皮尔逊相关系数: {psn_similarity}')

Bob与David的cosine相似度矩阵:
[[1.         0.63781505]
 [0.63781505 1.        ]] 

Bob与David的皮尔逊相关系数: (-0.9001487972234685, 0.037303521273850115)


In [12]:
# 物品A与物品B的相似性
cos_similarity = cosine_similarity([ratings.loc[:,'A'],ratings.loc[:,'B']])
psn_similarity = pearsonr(ratings.loc[:,'A'],ratings.loc[:,'B'])

print('物品A与物品B的cosine相似度矩阵:')
print(cos_similarity,'\n')
print(f'物品A与物品B的皮尔逊相关系数: {psn_similarity}')

物品A与物品B的cosine相似度矩阵:
[[1.         0.78025959]
 [0.78025959 1.        ]] 

物品A与物品B的皮尔逊相关系数: (-0.47673129462279606, 0.4168545738501419)


In [20]:
similarity = pearsonr([1,0,3,1,3],[3,1,3,3,5])
similarity

(0.7905694150420948, 0.11136715471408393)